#pragma once

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

//#define HYBRIDPIPE
#define WHIPPLETREE

#define VS_BINSIZE 32
#define RASTER_BINSIZE_LG2 3
#define RASTER_BINSIZE (1 << RASTER_BINSIZE_LG2)
